apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-db
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing_db
  template:
    metadata:
      labels:
        app: billing_db
    spec:
      containers:
        - name: billing-db
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "billing-service"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "12345"

---
apiVersion: v1
kind: Service
metadata:
  name: billing-db
  namespace: app-namespace
spec:
  selector:
    app: billing-db
  ports:
    - port: 5432
      targetPort: 5432