services:
  user_db:
    image: postgres:16
    container_name: userdb
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5437:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  product_db:
    image: postgres:16
    container_name: productdb
    environment:
      POSTGRES_DB: productservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  inventory_db:
    image: postgres:16
    container_name: inventorydb
    environment:
      POSTGRES_DB: inventoryservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  billing_db:
    image: postgres:16
    container_name: billingdb
    environment:
      POSTGRES_DB: billingservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5435:5432"
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  payment_db:
    image: postgres:16
    container_name: paymentdb
    environment:
      POSTGRES_DB: paymentservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5436:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: ./userservice/Dockerfile
      args:
        SERVICE_NAME: userservice
        COMMON_LIB_PATH: ./common-lib
    container_name: userservice
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/userservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      JWT_SECRET: ${JWT_SECRET}
      YANDEX_CLOUD_S3_ACCESS_KEY: ${YANDEX_CLOUD_S3_ACCESS_KEY}
      YANDEX_CLOUD_S3_SECRET_KEY: ${YANDEX_CLOUD_S3_SECRET_KEY}
    networks:
      - app-network

  product-service:
    build:
      context: .
      dockerfile: ./productservice/Dockerfile
      args:
        SERVICE_NAME: productservice
        COMMON_LIB_PATH: ./common-lib
    container_name: productservice
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://productdb:5432/productservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      YANDEX_CLOUD_S3_ACCESS_KEY: ${YANDEX_CLOUD_S3_ACCESS_KEY}
      YANDEX_CLOUD_S3_SECRET_KEY: ${YANDEX_CLOUD_S3_SECRET_KEY}
    networks:
      - app-network

  inventory-service:
    build:
      context: .
      dockerfile: ./inventoryservice/Dockerfile
      args:
        SERVICE_NAME: inventoryservice
        COMMON_LIB_PATH: ./common-lib
    container_name: inventoryservice
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventorydb:5432/inventoryservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - app-network

  billing-service:
    build:
      context: .
      dockerfile: ./billingservice/Dockerfile
      args:
        SERVICE_NAME: billingservice
        COMMON_LIB_PATH: ./common-lib
    container_name: billingservice
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://billingdb:5432/billingservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - app-network

  payment-service:
    build:
      context: .
      dockerfile: ./paymentservice/Dockerfile
      args:
        SERVICE_NAME: paymentservice
        COMMON_LIB_PATH: ./common-lib
    container_name: paymentservice
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://paymentdb:5432/paymentservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: ./apigatewayapplication/Dockerfile
      args:
        SERVICE_NAME: apigatewayapplication
        COMMON_LIB_PATH: ./common-lib
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

  admin-service:
    build:
      context: .
      dockerfile: ./adminservice/Dockerfile
      args:
        SERVICE_NAME: adminservice
        COMMON_LIB_PATH: ./common-lib
    container_name: adminservice
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

volumes:
  user_postgres_data:
  product_postgres_data:
  inventory_postgres_data:
  billing_postgres_data:
  payment_postgres_data:

networks:
  app-network:
    driver: bridge