version: '3.8'

services:
  user_db:
    image: postgres:16
    container_name: user_db;
    environment:
      - POSTGRES_DB=user-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  product_db:
    image: postgres:16
    container_name: product_db;
    environment:
      - POSTGRES_DB=product-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5433:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  inventory_db:
    image: postgres:16
    container_name: inventory_db;
    environment:
      - POSTGRES_DB=inventory-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5434:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  billing_db:
    image: postgres:16
    container_name: billing_db;
    environment:
      - POSTGRES_DB=billing-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5435:5432"
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  payment_db:
    image: postgres:16
    container_name: payment_db;
    environment:
      - POSTGRES_DB=payment-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5433:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: MyRedis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - app-network


  user-service:
    build:
      context: ./userservice
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_db:5432/user-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SERVER_PORT=8081
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - user_db
      - redis
    restart: unless-stopped
    networks:
      - app-network

  product-service:
    build:
      context: ./productservice
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product_db:5432/product-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SERVER_PORT=8082
    depends_on:
      - product_db
      - redis
    restart: unless-stopped
    networks:
      - app-network

  inventory-service:
    build:
      context: ./inventoryservice
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory_db:5432/inventory-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SERVER_PORT=8083
    depends_on:
      - inventory_db
      - redis
    restart: unless-stopped
    networks:
      - app-network