apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: app-namespace
  labels:
    app: inventory-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
        version: v1
    spec:
      containers:
        - name: inventory-service
          image: vegapankclub-inventory-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8083
              protocol: TCP

          env:
            - name: SPRING_LIQUIBASE_CHANGE_LOG
              value: "classpath:db/changelog/db.changelog-master.xml"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://inventory-db:5432/inventory-service"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 180
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always


