apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: app-namespace
  labels:
    app: user-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      containers:
        - name: user-service
          image: vegapankclub-user-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081
              protocol: TCP

          env:
            - name: SPRING_LIQUIBASE_CHANGE_LOG
              value: "classpath:db/changelog/db.changelog-master.xml"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://user-db:5432/user-service"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SERVER_PORT
              value: "8081"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: YANDEX_CLOUD_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: yandex-cloud-s3-access-key
            - name: YANDEX_CLOUD_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: yandex-cloud-s3-secret-key

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always


