name: CI/CD for UserService

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    name: Build userService
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Install common-lib
        run: |
          cd common-lib
          mvn -B clean install -DskipTests=true

      - name: Build project
        run: |
          cd userservice
          mvn -B clean package -DskipTests=true

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Install common-lib
        run: |
          cd common-lib
          mvn -B clean install -DskipTests=true

      - name: Run tests
        run: |
          cd userservice
          mvn -B test

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Install common-lib
        run: |
          cd common-lib
          mvn -B clean install -DskipTests=true

      - name: Build JAR file
        run: |
          cd userservice
          mvn -B clean package -DskipTests=true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_KIRILL }}
          password: ${{ secrets.DOCKER_PASSWORD_KIRILL }}

      - name: Build Docker image
        run: |
          cd userservice
          docker build -t ${{ secrets.DOCKER_USERNAME_KIRILL }}/userservice:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME_KIRILL }}/userservice:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME_KIRILL }}/userservice:${{ github.sha }} ${{ secrets.DOCKER_USERNAME_KIRILL }}/userservice:latest
          docker push ${{ secrets.DOCKER_USERNAME_KIRILL }}/userservice:latest
